### ISSUE TITLE
Consider using the D/Phobos style conventions

### ISSUE THREAD

**Issue by GeorgeSapkin** [etcimon/libasync#16]
Is there any reason why you are not using [the D style conventions](http://dlang.org/dstyle.html)? Spaces instead of tabs and braces on own lines in particular.

**Comment by etcimon** [comment]
I don't yet have .editorconfig in Mono-D and the default is tabs as tabs, so I just kept going with that. I guess I'll have to change that soon enough

**Comment by etcimon** [comment]
> braces on own lines

Depends on the length of the line, I don't particularly crave line counts over readability

**Comment by wilzbach** [comment]
I know this might not be that pleasant, but if you want libasync to be included in Phobos (and I hope you do propose that soon), it has to use the Phobos style. There is also [dfmt](https://github.com/Hackerpilot/dfmt)

**Comment by etcimon** [comment]
I'll probably do that soon enough, I'm freeing myself up slowly for it. I think expanding the standard library with event-based (thread-local) concurrency would benefit the whole D community. I would prefer seeing this added to druntime in core.event so that you can have fiber-blocking synchronization primitives in core.sync and a fiber scheduler in core.thread, but it's still developing slowly in my mind
