### ISSUE TITLE
Very verbose output while using libasync within vibe-d

### ISSUE THREAD

**Issue by andre2007** [etcimon/libasync#82]
I am not sure wether this issue is more libasync related or vibe-d related.
The output is very verbose. There are a lot of lines with the same text:

Using Linux EPOLL for events
Enhanced memory security is enabled
Memory debugger enabled
...
Using Linux EPOLL for events
Enhanced memory security is enabled
Memory debugger enabled
...

In my case it is even worse, I am forced to compile vibe-d in single file compilation mode due to restriced RAM. Therefore I see a lot of these lines. Is it possible to show these information only once?

In addition, why is there a memory debugger enabled?

**Comment by etcimon** [comment]
I think the verbose could be avoided if there is a static if condition telling us whether this package is being compiled or if its another. Because the pragma will run every time a package that uses libasync compiles.

Also, the memory debugger is in memutils and adds many assertions to know e.g if a pointer that should be unique is found in another Unique object ie. escaped reference. You can disableit with DisableDebugger

**Comment by etcimon** [comment]
I don't think anyone is going to be using libasync in vibe.d anymore, the implementation was removed when migrating to the `eventcore` submodule and I don't have time to rework it when in the end my vibe fork has many more features such as tls1.3 http2 cookiejars pgsql and so on whereas the merging process at this point seems very complicated with vibe.d authors.
